[build]
  base = "."
  command = "npm run build:web"
  publish = "dist"

[build.environment]
  NODE_VERSION = "18"
  EXPO_PUBLIC_API_URL = "https://scripture-quest-api.vercel.app"

[[redirects]]
  from = "/api/*"
  to = "https://scripture-quest-api.vercel.app/api/:splat"
  status = 200
  force = true

[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200

[context.production.environment]
  EXPO_PUBLIC_DEBUG_MODE = "false"
  EXPO_PUBLIC_LOG_LEVEL = "error"

[context.deploy-preview.environment]
  EXPO_PUBLIC_DEBUG_MODE = "true"
  EXPO_PUBLIC_LOG_LEVEL = "debug"

[[headers]]
  for = "/*"
  [headers.values]
    X-Frame-Options = "DENY"
    X-XSS-Protection = "1; mode=block"
    X-Content-Type-Options = "nosniff"
    Referrer-Policy = "strict-origin-when-cross-origin"

[[headers]]
  for = "/static/*"
  [headers.values]
    Cache-Control = "public, max-age=31536000, immutable"